# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMessageTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('n54ID', models.IntegerField()),
                ('n54URL', models.URLField()),
                ('parentID', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ForumMessageModel',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='parentID',
            field=models.IntegerField(null=True),
        ),
    ]
