# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forummessagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='forummessagemodel',
            name='bodylen',
            field=models.IntegerField(null=True),
        ),
    ]
